name: Deploy Gabicake Microfrontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Mensagem inicial
        run: echo "Iniciando deploy do Gabicake..."

      - name: Disparar Deploy Vercel
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
